language: c
compiler:
  - gcc
  - clang
install:
  - sudo apt-get install acpi
  - sudo apt-get install chicken-bin
  - sudo apt-get install libchicken6
script:
  - autoreconf -fi && ./configure && make
