language: c
compiler:
  - clang
  - gcc-4.4
  - gcc-4.5
  - gcc-4.6
  - gcc-4.8
install:
  - sudo apt-get update
  - sudo apt-get install gcc-4.4 gcc-4.5 gcc-4.6 gcc-4.8
  - sudo apt-get install libacpi-dev
script:
  - autoreconf -i
  - ./configure
  - make
after_success:
  - make check
