language: c
compiler:
  - clang
  - gcc-4.4
install:
  - sudo apt-get update
  - sudo apt-get install gcc-4.4
  - sudo apt-get install libacpi-dev
script:
  - autoreconf -i
  - ./configure
  - make
after_success:
  - make check
