language: c
compiler:
  - clang
  - gcc-4.4
  - gcc-4.5
  - gcc-4.6
install:
  - sudo apt-get update
  - sudo apt-get install gcc-4.4 gcc-4.5 gcc-4.6 chicken-bin
  - sudo chicken-install test
script:
  - autoreconf -i
  - ./configure --without-gtk2
  - make clean
  - make
after_success:
  - src/zbatt
  - src/zbatc
  - make clean
  - ./configure --without-gtk2 CFLAGS=-DZB_DEBUG=0
  - make check
