language: c
compiler:
  - clang
  - gcc
  - gcc-4.4
  - gcc-4.5
  - gcc-4.6
install:
  - sudo apt-get update
  - sudo apt-get install gcc-4.4 gcc-4.5 gcc-4.6
  - sudo apt-get install acpi
  - sudo apt-get install chicken-bin
  - sudo apt-get install libchicken6
  - sudo chicken-install shell srfi-1 regex list-utils posix
script:
  - autoreconf -fi
  - ./configure
  - make
  - ./configure --enable-native
  - make anew
  - ./configure --enable-generic
  - make anew
after_success:
  - sudo apt-get install yacpi
  - sudo apt-get remove acpi
  - autoreconf -fi
  - ./configure
  - make anew
  - ./configure --enable-native
  - make anew
  - ./configure --enable-generic
  - make anew
