language: c
compiler:
  - gcc
  - clang
install:
  - sudo apt-get install acpi
  - sudo apt-get install chicken-bin
  - sudo apt-get install libchicken6
  - sudo chicken-install ansi-escape-sequences shell srfi-1
script:
  - autoreconf -fi && ./configure && make
