language: c
compiler:
  - clang
  - gcc
  - gcc-4.4
  - gcc-4.7
install:
  - sudo apt-get update
  - sudo apt-get install gcc-4.4 gcc-4.7
  - sudo apt-get install libacpi-dev
script:
  - autoreconf -i
  - ./configure
  - make
after_success:
  - ./zelda-demo.sh
